name: Telegram Notification

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - '*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit details
        id: commit
        run: |
          echo "message=$(git log -1 --pretty=format:%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=format:%an)" >> $GITHUB_OUTPUT

      - name: Send Telegram notification
        run: |
          export AUTHOR="${{ steps.commit.outputs.author }}"
          export REPO="${GITHUB_REPOSITORY##*/}"
          export REF="${GITHUB_REF##*/}"
          export COMMIT_MSG="${{ steps.commit.outputs.message }}"
          export REPO_URL="https://github.com/$GITHUB_REPOSITORY"
          
          # Xác định loại event và thiết lập thông báo phù hợp
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            export MESSAGE="🚀 New Release%0A%0A<code>$REPO</code>: Tag <code>$REF</code>%0A$COMMIT_MSG%0Aby $AUTHOR%0A%0A$REPO_URL"
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            export MESSAGE="📝 New Push%0A%0A<code>$REPO</code>: Branch <code>$REF</code>%0A$COMMIT_MSG%0Aby $AUTHOR%0A%0A$REPO_URL/commit/${{ github.sha }}"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            export PR_TITLE="${{ github.event.pull_request.title }}"
            export PR_URL="${{ github.event.pull_request.html_url }}"
            export PR_NUM="${{ github.event.pull_request.number }}"
            export MESSAGE="🔍 New Pull Request #$PR_NUM%0A%0A<code>$REPO</code>%0A$PR_TITLE%0Aby $AUTHOR%0A%0A$PR_URL"
          else
            export MESSAGE="⚡ Repository Activity%0A%0A<code>$REPO</code>%0A$COMMIT_MSG%0Aby $AUTHOR%0A%0A$REPO_URL"
          fi
          
          curl -s -X POST \
            -d "parse_mode=HTML&chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$MESSAGE" \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage
